const bcrypt = require('bcryptjs');
const { pool, query } = require('../config/db');

const SCHEMA_SQL = `
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- 1. Profiles (Admins & Staff)
CREATE TABLE IF NOT EXISTS profiles (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  email TEXT UNIQUE NOT NULL,
  password_hash TEXT,
  full_name TEXT,
  role TEXT NOT NULL DEFAULT 'admin' CHECK (role IN ('admin', 'super_admin')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 2. Company Settings (Singleton row)
CREATE TABLE IF NOT EXISTS company_settings (
  id INTEGER PRIMARY KEY DEFAULT 1,
  company_name TEXT NOT NULL DEFAULT 'Nature Farming',
  tagline TEXT DEFAULT 'Sri Lanka''s Leading Aloe Vera Partner',
  logo_url TEXT,
  head_office_address TEXT,
  primary_phone TEXT,
  secondary_phone TEXT,
  primary_email TEXT,
  whatsapp_number TEXT,
  facebook_link TEXT,
  instagram_link TEXT,
  youtube_link TEXT,
  about_us TEXT,
  mission TEXT,
  vision TEXT,
  total_farmers INTEGER NOT NULL DEFAULT 5000,
  districts_count INTEGER NOT NULL DEFAULT 12,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT company_settings_singleton CHECK (id = 1)
);

-- 3. Product Categories
CREATE TABLE IF NOT EXISTS product_categories (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name TEXT NOT NULL,
  slug TEXT UNIQUE NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 4. Products
CREATE TABLE IF NOT EXISTS products (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name TEXT NOT NULL,
  slug TEXT UNIQUE NOT NULL,
  description TEXT,
  benefits TEXT[],
  price NUMERIC(10,2),
  image_url TEXT,
  category_id UUID REFERENCES product_categories(id) ON DELETE SET NULL,
  is_featured BOOLEAN NOT NULL DEFAULT FALSE,
  is_published BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 5. Branches
CREATE TABLE IF NOT EXISTS branches (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name TEXT NOT NULL,
  district TEXT NOT NULL,
  address TEXT NOT NULL,
  phone TEXT,
  email TEXT,
  map_url TEXT,
  manager_name TEXT,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 6. Inquiries
CREATE TABLE IF NOT EXISTS inquiries (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  type TEXT NOT NULL CHECK (type IN ('contact', 'farmer_interest')),
  full_name TEXT NOT NULL,
  email TEXT,
  phone TEXT NOT NULL,
  subject TEXT,
  message TEXT,
  district TEXT,
  assigned_branch_id UUID REFERENCES branches(id) ON DELETE SET NULL,
  status TEXT NOT NULL DEFAULT 'new' CHECK (status IN ('new', 'contacted', 'closed')),
  admin_notes TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 7. Gallery
CREATE TABLE IF NOT EXISTS gallery (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  title TEXT,
  image_url TEXT NOT NULL,
  category TEXT NOT NULL DEFAULT 'other' CHECK (category IN ('farms', 'production', 'products', 'farmers', 'other', 'journey')),
  display_order INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 8. FAQs
CREATE TABLE IF NOT EXISTS faqs (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  question TEXT NOT NULL,
  answer TEXT NOT NULL,
  display_order INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 9. Ads & Banners
CREATE TABLE IF NOT EXISTS ads_banners (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  title TEXT,
  image_url TEXT NOT NULL,
  link TEXT,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  display_order INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 10. Inquiry Rate Limits
CREATE TABLE IF NOT EXISTS inquiry_rate_limits (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ip_hash TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Indexes
CREATE INDEX IF NOT EXISTS products_public_idx ON products (is_published, is_featured, created_at DESC);
CREATE INDEX IF NOT EXISTS branches_public_idx ON branches (is_active, name);
CREATE INDEX IF NOT EXISTS inquiries_created_idx ON inquiries (created_at DESC);
CREATE INDEX IF NOT EXISTS inquiries_status_idx ON inquiries (status, created_at DESC);
CREATE INDEX IF NOT EXISTS inquiries_branch_idx ON inquiries (assigned_branch_id);
CREATE INDEX IF NOT EXISTS gallery_order_idx ON gallery (display_order, created_at DESC);
CREATE INDEX IF NOT EXISTS banners_public_idx ON ads_banners (is_active, display_order);
CREATE INDEX IF NOT EXISTS inquiry_rate_limit_idx ON inquiry_rate_limits (ip_hash, created_at DESC);
`;

async function initializeDatabase() {
  console.log('🔄 Initializing Nature Farming PostgreSQL Database...');
  try {
    // 1. Execute Table Definitions
    await query(SCHEMA_SQL);
    console.log('✅ Tables and indexes created successfully.');

    // 2. Default Company Settings
    const settingsCheck = await query('SELECT id FROM company_settings WHERE id = 1');
    if (settingsCheck.rows.length === 0) {
      await query(`
        INSERT INTO company_settings (
          id, company_name, tagline, head_office_address, 
          primary_phone, primary_email, whatsapp_number,
          total_farmers, districts_count
        ) VALUES (
          1, 'Nature Farming (Pvt) Ltd', 'Sri Lanka''s Leading Aloe Vera Partner',
          'Northern & Eastern Agricultural Zones, Sri Lanka',
          '+94 77 123 4567', 'info@nfplantation.com', '+94771234567',
          5000, 12
        )
      `);
      console.log('✅ Default company settings inserted.');
    }

    // 3. Default Product Categories
    const categories = [
      { name: 'Personal Care', slug: 'personal-care' },
      { name: 'Raw Materials', slug: 'raw-materials' },
      { name: 'Agriculture', slug: 'agriculture' },
    ];
    for (const cat of categories) {
      await query(`
        INSERT INTO product_categories (name, slug)
        VALUES ($1, $2)
        ON CONFLICT (slug) DO NOTHING
      `, [cat.name, cat.slug]);
    }
    console.log('✅ Default categories verified.');

    // 4. Default Super Admin User
    const adminEmail = process.env.DEFAULT_ADMIN_EMAIL || 'admin@nfplantation.com';
    const adminPassword = process.env.DEFAULT_ADMIN_PASSWORD || 'Admin@123456';
    const adminName = process.env.DEFAULT_ADMIN_NAME || 'Super Administrator';

    const adminCheck = await query('SELECT id, role, password_hash FROM profiles WHERE email = $1', [adminEmail]);

    if (adminCheck.rows.length === 0) {
      const salt = await bcrypt.genSalt(10);
      const hash = await bcrypt.hash(adminPassword, salt);
      await query(`
        INSERT INTO profiles (email, password_hash, full_name, role)
        VALUES ($1, $2, $3, 'super_admin')
      `, [adminEmail, hash, adminName]);
      console.log(`✅ Default Super Admin created! Email: ${adminEmail} | Password: ${adminPassword}`);
    } else if (!adminCheck.rows[0].password_hash) {
      // Set password if migrated from Supabase without password hash
      const salt = await bcrypt.genSalt(10);
      const hash = await bcrypt.hash(adminPassword, salt);
      await query(`
        UPDATE profiles SET password_hash = $1, role = 'super_admin' WHERE email = $2
      `, [hash, adminEmail]);
      console.log(`✅ Updated existing profile with password hash for ${adminEmail}`);
    } else {
      console.log(`ℹ️ Admin user ${adminEmail} already exists.`);
    }

    console.log('🎉 Database initialization complete!');
  } catch (error) {
    if (error.code === 'ECONNREFUSED' || (error.errors && error.errors[0]?.code === 'ECONNREFUSED')) {
      console.error('\n⚠️ Could not connect to PostgreSQL (ECONNREFUSED).');
      console.error('👉 Please ensure PostgreSQL is running, or set your remote DATABASE_URL in backend/.env');
    } else {
      console.error('❌ Database initialization failed:', error.message || error);
    }
    process.exit(1);
  } finally {
    await pool.end();
  }
}

if (require.main === module) {
  initializeDatabase();
}

module.exports = { initializeDatabase };
