INSERT INTO public.branches (name, district, address, manager_name, email, phone) VALUES
('Chavakachcheri', 'Chavakachcheri', 'Chavakachcheri', 'KAANDIPAN ABISHAJAN', 'nfplantationas@gmail.com', '706189612'),
('Chavakachcheri', 'Chavakachcheri', 'Chavakachcheri', 'KIRUBANANTHAN KEERTHAAN', 'nfplantationkt@gmail.com', '0743426403'),
('Kilinochchi', 'Kilinochchi', 'Kilinochchi', 'SRIKANTHAN KALAIVANY', 'skalai0714@gmail.com', '776355774'),
('Puthukkudiyiruppu', 'Puthukkudiyiruppu', 'Puthukkudiyiruppu', 'SASIKKUMAR MAHILINY', 'silampusilamparasan55@gmail.com', '764243506'),
('Mulliyawalai', 'Mulliyawalai', 'Mulliyawalai', 'KAGILAITHIRUNATHAN VITHUSAN', 'vithusanvithu291@gmail.com', '774844182'),
('Mallavi', 'Mallavi', 'Mallavi', 'KIRUSHNAMOORTHI THARMARANY', 'tharmaranibanu@gmail.com', '775851256'),
('Nedunkeny', 'Nedunkeny', 'Nedunkeny', 'MODSARASA PURADSIKA', 'pmodsarasa@gmail.com', '766448018'),
('Thirunelvelly', 'Thirunelvelly', 'Thirunelvelly', 'VIJAYARATNAM GOWRIKASAN', 'v.ragisan@gmail.com', '775474745'),
('Karachchi', 'Karachchi', 'Karachchi', 'JEGARAJASEKARAM KARTHIGA', 'karthigakarththi@gmail.com', '770232509'),
('Poonakary', 'Poonakary', 'Poonakary', 'PARAMESWARAN ANUSHAN', 'anushan.bavi@gmail.com', '770055759'),
('Kandawalai', 'Kandawalai', 'Kandawalai', 'JEKATHEESVARAN NILOJANA', 'nilonilo947@gmail.com', '768269378'),
('Vavuniya', 'Vavuniya', 'Vavuniya', 'RAGEEVKARAN LOGINI', 'logil1833@gmail.com', '773520629'),
('Akkaraipattu', 'Akkaraipattu', 'Akkaraipattu', 'KOPAL JEEVITHA', 'preshwinr@gmail.com', '755392402'),
('Ampara', 'Ampara', 'Ampara', 'ABDAL RAHUMAN SULKIFLY AHAMED', 'kiflyahamed@gmail.com', '777251128'),
('Cheddikulam', 'Cheddikulam', 'Cheddikulam', 'Sithmbaram Subanthini', 'subanthini29@gmail.com', '773830680'),
('Kalmunai', 'Kalmunai', 'Kalmunai', 'VAIRAMUTHU LOGINI', 'gayathrigayagaya8@gmail.com', '763015040'),
('Mannar', 'Mannar', 'Mannar', 'Anne Rucksini Thomas.Culas', 'annerucksini@gmail.com', '0757076946'),
('Kalmunai', 'Kalmunai', 'Kalmunai', 'Branch Manager One', 'manager1@naturefarming.com', '0712345678');