-- Nature Farming production backend for Supabase
-- Safe to run more than once. Existing business data is preserved.

create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text unique not null,
  full_name text,
  role text not null default 'admin',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.company_settings (
  id integer primary key default 1,
  company_name text not null default 'Nature Farming',
  tagline text,
  logo_url text,
  head_office_address text,
  primary_phone text,
  secondary_phone text,
  primary_email text,
  whatsapp_number text,
  facebook_link text,
  instagram_link text,
  youtube_link text,
  about_us text,
  mission text,
  vision text,
  total_farmers integer not null default 5000,
  districts_count integer not null default 12,
  updated_at timestamptz not null default now(),
  constraint company_settings_singleton check (id = 1)
);

create table if not exists public.product_categories (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  slug text unique not null,
  created_at timestamptz not null default now()
);

create table if not exists public.products (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  slug text unique not null,
  description text,
  benefits text[],
  price numeric(10,2),
  image_url text,
  category_id uuid references public.product_categories(id) on delete set null,
  is_featured boolean not null default false,
  is_published boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.branches (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  district text not null,
  address text not null,
  phone text,
  email text,
  map_url text,
  manager_name text,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.inquiries (
  id uuid primary key default gen_random_uuid(),
  type text not null,
  full_name text not null,
  email text,
  phone text not null,
  subject text,
  message text,
  district text,
  assigned_branch_id uuid references public.branches(id) on delete set null,
  status text not null default 'new',
  admin_notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.gallery (
  id uuid primary key default gen_random_uuid(),
  title text,
  image_url text not null,
  category text not null default 'other',
  display_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.faqs (
  id uuid primary key default gen_random_uuid(),
  question text not null,
  answer text not null,
  display_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.ads_banners (
  id uuid primary key default gen_random_uuid(),
  title text,
  image_url text not null,
  link text,
  is_active boolean not null default true,
  display_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Privacy-preserving API abuse tracking. Only the server service role accesses it.
create table if not exists public.inquiry_rate_limits (
  id bigint generated by default as identity primary key,
  ip_hash text not null,
  created_at timestamptz not null default now()
);

-- Bring older installations up to the current shape.
alter table public.company_settings add column if not exists total_farmers integer not null default 5000;
alter table public.company_settings add column if not exists districts_count integer not null default 12;
alter table public.inquiries add column if not exists assigned_branch_id uuid references public.branches(id) on delete set null;
alter table public.inquiries add column if not exists updated_at timestamptz not null default now();
alter table public.gallery add column if not exists updated_at timestamptz not null default now();
alter table public.faqs add column if not exists updated_at timestamptz not null default now();

update public.inquiries set status = 'closed' where status = 'resolved';
update public.gallery set category = 'farms' where category = 'farm';

alter table public.profiles drop constraint if exists profiles_role_check;
alter table public.profiles add constraint profiles_role_check check (role in ('admin', 'super_admin'));
alter table public.inquiries drop constraint if exists inquiries_type_check;
alter table public.inquiries add constraint inquiries_type_check check (type in ('contact', 'farmer_interest'));
alter table public.inquiries drop constraint if exists inquiries_status_check;
alter table public.inquiries add constraint inquiries_status_check check (status in ('new', 'contacted', 'closed'));
alter table public.gallery drop constraint if exists gallery_category_check;
alter table public.gallery add constraint gallery_category_check check (category in ('farms', 'production', 'products', 'farmers', 'other'));
alter table public.products drop constraint if exists products_price_check;
alter table public.products add constraint products_price_check check (price is null or price >= 0);

create index if not exists products_public_idx on public.products (is_published, is_featured, created_at desc);
create index if not exists branches_public_idx on public.branches (is_active, name);
create index if not exists inquiries_created_idx on public.inquiries (created_at desc);
create index if not exists inquiries_status_idx on public.inquiries (status, created_at desc);
create index if not exists inquiries_branch_idx on public.inquiries (assigned_branch_id);
create index if not exists gallery_order_idx on public.gallery (display_order, created_at desc);
create index if not exists banners_public_idx on public.ads_banners (is_active, display_order);
create index if not exists inquiry_rate_limit_idx on public.inquiry_rate_limits (ip_hash, created_at desc);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists profiles_set_updated_at on public.profiles;
create trigger profiles_set_updated_at before update on public.profiles for each row execute function public.set_updated_at();
drop trigger if exists settings_set_updated_at on public.company_settings;
create trigger settings_set_updated_at before update on public.company_settings for each row execute function public.set_updated_at();
drop trigger if exists products_set_updated_at on public.products;
create trigger products_set_updated_at before update on public.products for each row execute function public.set_updated_at();
drop trigger if exists branches_set_updated_at on public.branches;
create trigger branches_set_updated_at before update on public.branches for each row execute function public.set_updated_at();
drop trigger if exists inquiries_set_updated_at on public.inquiries;
create trigger inquiries_set_updated_at before update on public.inquiries for each row execute function public.set_updated_at();
drop trigger if exists gallery_set_updated_at on public.gallery;
create trigger gallery_set_updated_at before update on public.gallery for each row execute function public.set_updated_at();
drop trigger if exists faqs_set_updated_at on public.faqs;
create trigger faqs_set_updated_at before update on public.faqs for each row execute function public.set_updated_at();
drop trigger if exists banners_set_updated_at on public.ads_banners;
create trigger banners_set_updated_at before update on public.ads_banners for each row execute function public.set_updated_at();

-- No Auth signup automatically receives an admin role.
drop trigger if exists on_auth_user_created on auth.users;
drop function if exists public.handle_new_user();

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1 from public.profiles
    where id = (select auth.uid()) and role in ('admin', 'super_admin')
  );
$$;

create or replace function public.is_super_admin()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1 from public.profiles
    where id = (select auth.uid()) and role = 'super_admin'
  );
$$;

revoke all on function public.is_admin() from public;
revoke all on function public.is_super_admin() from public;
grant execute on function public.is_admin() to authenticated, service_role;
grant execute on function public.is_super_admin() to authenticated, service_role;

alter table public.profiles enable row level security;
alter table public.company_settings enable row level security;
alter table public.product_categories enable row level security;
alter table public.products enable row level security;
alter table public.branches enable row level security;
alter table public.inquiries enable row level security;
alter table public.gallery enable row level security;
alter table public.faqs enable row level security;
alter table public.ads_banners enable row level security;
alter table public.inquiry_rate_limits enable row level security;

-- Remove legacy/permissive policies before installing production policies.
drop policy if exists "Admins can view all profiles" on public.profiles;
drop policy if exists "Public Read Settings" on public.company_settings;
drop policy if exists "Public Read Categories" on public.product_categories;
drop policy if exists "Public Read Products" on public.products;
drop policy if exists "Public Read Branches" on public.branches;
drop policy if exists "Public Read Gallery" on public.gallery;
drop policy if exists "Public Read FAQs" on public.faqs;
drop policy if exists "Anyone can submit inquiries" on public.inquiries;
drop policy if exists "Admins full access settings" on public.company_settings;
drop policy if exists "Admins full access categories" on public.product_categories;
drop policy if exists "Admins full access products" on public.products;
drop policy if exists "Admins full access branches" on public.branches;
drop policy if exists "Admins full access inquiries" on public.inquiries;
drop policy if exists "Admins full access gallery" on public.gallery;
drop policy if exists "Admins full access faqs" on public.faqs;

drop policy if exists profiles_read_self on public.profiles;
drop policy if exists profiles_manage_super_admin on public.profiles;
drop policy if exists settings_public_read on public.company_settings;
drop policy if exists settings_admin_manage on public.company_settings;
drop policy if exists categories_public_read on public.product_categories;
drop policy if exists categories_admin_manage on public.product_categories;
drop policy if exists products_public_read on public.products;
drop policy if exists products_admin_manage on public.products;
drop policy if exists branches_public_read on public.branches;
drop policy if exists branches_admin_manage on public.branches;
drop policy if exists inquiries_admin_manage on public.inquiries;
drop policy if exists gallery_public_read on public.gallery;
drop policy if exists gallery_admin_manage on public.gallery;
drop policy if exists faqs_public_read on public.faqs;
drop policy if exists faqs_admin_manage on public.faqs;
drop policy if exists banners_public_read on public.ads_banners;
drop policy if exists banners_admin_manage on public.ads_banners;

create policy profiles_read_self on public.profiles for select to authenticated
  using (id = (select auth.uid()) or public.is_super_admin());
create policy profiles_manage_super_admin on public.profiles for all to authenticated
  using (public.is_super_admin()) with check (public.is_super_admin());

create policy settings_public_read on public.company_settings for select to anon, authenticated using (true);
create policy settings_admin_manage on public.company_settings for all to authenticated using (public.is_admin()) with check (public.is_admin());
create policy categories_public_read on public.product_categories for select to anon, authenticated using (true);
create policy categories_admin_manage on public.product_categories for all to authenticated using (public.is_admin()) with check (public.is_admin());
create policy products_public_read on public.products for select to anon, authenticated using (is_published);
create policy products_admin_manage on public.products for all to authenticated using (public.is_admin()) with check (public.is_admin());
create policy branches_public_read on public.branches for select to anon, authenticated using (is_active);
create policy branches_admin_manage on public.branches for all to authenticated using (public.is_admin()) with check (public.is_admin());
create policy inquiries_admin_manage on public.inquiries for all to authenticated using (public.is_admin()) with check (public.is_admin());
create policy gallery_public_read on public.gallery for select to anon, authenticated using (true);
create policy gallery_admin_manage on public.gallery for all to authenticated using (public.is_admin()) with check (public.is_admin());
create policy faqs_public_read on public.faqs for select to anon, authenticated using (true);
create policy faqs_admin_manage on public.faqs for all to authenticated using (public.is_admin()) with check (public.is_admin());
create policy banners_public_read on public.ads_banners for select to anon, authenticated using (is_active);
create policy banners_admin_manage on public.ads_banners for all to authenticated using (public.is_admin()) with check (public.is_admin());

revoke all on public.inquiries from anon;
revoke all on public.inquiry_rate_limits from anon, authenticated;
grant select on public.company_settings, public.product_categories, public.products, public.branches, public.gallery, public.faqs, public.ads_banners to anon;
grant select, insert, update, delete on public.profiles, public.company_settings, public.product_categories, public.products, public.branches, public.inquiries, public.gallery, public.faqs, public.ads_banners to authenticated;
grant all on public.inquiries, public.inquiry_rate_limits to service_role;
grant usage, select on sequence public.inquiry_rate_limits_id_seq to service_role;

insert into public.company_settings (id, company_name, tagline)
values (1, 'Nature Farming', 'Sri Lanka''s Leading Aloe Vera Partner')
on conflict (id) do nothing;

insert into public.product_categories (name, slug) values
  ('Personal Care', 'personal-care'),
  ('Raw Materials', 'raw-materials'),
  ('Agriculture', 'agriculture')
on conflict (slug) do nothing;

-- Public buckets; writes remain restricted by storage object policies below.
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values
  ('gallery', 'gallery', true, 5242880, array['image/jpeg', 'image/png', 'image/webp']),
  ('banners', 'banners', true, 5242880, array['image/jpeg', 'image/png', 'image/webp'])
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists media_public_read on storage.objects;
drop policy if exists media_admin_insert on storage.objects;
drop policy if exists media_admin_update on storage.objects;
drop policy if exists media_admin_delete on storage.objects;

create policy media_public_read on storage.objects for select to anon, authenticated
  using (bucket_id in ('gallery', 'banners'));
create policy media_admin_insert on storage.objects for insert to authenticated
  with check (bucket_id in ('gallery', 'banners') and public.is_admin());
create policy media_admin_update on storage.objects for update to authenticated
  using (bucket_id in ('gallery', 'banners') and public.is_admin())
  with check (bucket_id in ('gallery', 'banners') and public.is_admin());
create policy media_admin_delete on storage.objects for delete to authenticated
  using (bucket_id in ('gallery', 'banners') and public.is_admin());

-- After creating a user in Supabase Auth, bootstrap the first administrator with:
-- insert into public.profiles (id, email, full_name, role)
-- select id, email, 'Administrator', 'super_admin'
-- from auth.users where email = 'YOUR_ADMIN_EMAIL';
